---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true
  require_chef_omnibus: 12.19.36

verifier:
  name: inspec

platforms:
  - name: centos-7.2
    driver_config:
      network:
      - ["private_network", {ip: "192.168.33.23"}]

    driver:
      box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-7.2_chef-provisionerless.box


suites:
  - name: core-mysql
    run_list:
      - recipe[aps-core::default]
      - recipe[aps-core::redeploy]
      - recipe[alfresco-utils::node_json]
    verifier:
       inspec_tests:
        - name: chef-aps-inspec-core
          git: https://github.com/Alfresco/chef-aps-inspec-core
        - name: chef-aps-inspec-tomcat
          git: https://github.com/Alfresco/chef-aps-inspec-tomcat
    attributes: {
      "aps-core" : {
        "version" : "1.6.0",
        "nexus" : {
          "username" : "<%= ENV['NEXUS_USERNAME'] %>",
          "password" : "<%= ENV['NEXUS_PASSWORD'] %>"
        },
        "db" : {
          "engine" : "mysql"
          }
        }
      }
  - name: core-postgres
    run_list:
      - recipe[aps-core::default]
      - recipe[aps-core::redeploy]
      - recipe[alfresco-utils::node_json]
    verifier:
       inspec_tests:
        - name: chef-aps-inspec-core
          git: https://github.com/Alfresco/chef-aps-inspec-core
        - name: chef-aps-inspec-tomcat
          git: https://github.com/Alfresco/chef-aps-inspec-tomcat
    attributes: {
      "aps-core" : {
        "version" : "1.6.0",
        "nexus" : {
          "username" : "<%= ENV['NEXUS_USERNAME'] %>",
          "password" : "<%= ENV['NEXUS_PASSWORD'] %>"
        },
        "db" : {
          "engine" : "postgres"
          }
        }
     }
