language: ruby
rvm: 2.3.1

sudo: required
services: docker

env:
  matrix:
    - SUITE=default

before_install: curl -L https://www.getchef.com/chef/install.sh | sudo bash -s -- -P chefdk -v 1.2.20
install: bundle install

before_script: sudo iptables -L DOCKER || sudo iptables -N DOCKER

script:
  - chef exec rake default
  # Run test-kitchen with docker driver, for example:
  - chef exec bundle exec rake "integration:docker[$SUITE, test]"
